Update main.yml
Signed-off-by: Pawel Paszki <ppaszki@redhat.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,7 +13,9 @@ jobs:
     steps:
       # start test
       - name: dummy test
-        run: sleep 300
+        run: |
+          # sleep 300 # test success
+          sleep 300 & exit 1 # test failure
       
       # end test
       # - name: Checkout kuberay Repository
